import { Deal } from './types';
import { subtractDays } from './utils';

export const initialDeals: Deal[] = [

  // ── ORIGINAL: Active pipeline (12 deals) ────────────────────────
  {
    id: 'd01',
    account: 'Acme Corp',
    value: '₹8.5L',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(2),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-01a', filename: 'Acme_Proposal_v2.pdf', uploadedAt: subtractDays(2) },
    ],
  },
  {
    id: 'd02',
    account: 'Globex Industries',
    value: '$42K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(5),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd03',
    account: 'Initech Solutions',
    value: '£15K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(9),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-03a', filename: 'Initech_Intro_Deck.pdf', uploadedAt: subtractDays(9) },
    ],
  },
  {
    id: 'd04',
    account: 'Hooli Cloud',
    value: 'AUD 60K',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(1),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-04a', filename: 'Hooli_Proposal_Final.pdf', uploadedAt: subtractDays(1) },
    ],
  },
  {
    id: 'd05',
    account: 'Stark Tech',
    value: 'MYR 80K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(3),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-05a', filename: 'StarkTech_DemoNotes.docx', uploadedAt: subtractDays(3) },
    ],
  },
  {
    id: 'd06',
    account: 'Wayne Enterprises',
    value: 'R$ 120K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(4),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-06a', filename: 'Wayne_OutreachSummary.pdf', uploadedAt: subtractDays(4) },
    ],
  },
  {
    id: 'd07',
    account: 'Wonka Industries',
    value: 'AED 50K',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(6),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd08',
    account: 'Pied Piper',
    value: '₹6L',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(11),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-08a', filename: 'PiedPiper_FirstContact.pdf', uploadedAt: subtractDays(11) },
    ],
  },
  {
    id: 'd09',
    account: 'Massive Dynamic',
    value: '£25K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(5),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-09a', filename: 'MassiveDynamic_DemoRecap.pdf', uploadedAt: subtractDays(5) },
    ],
  },
  {
    id: 'd10',
    account: 'Cyberdyne Systems',
    value: 'AUD 90K',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(8),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd11',
    account: 'Soylent Corp',
    value: 'AED 35K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(2),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-11a', filename: 'Soylent_InitialBrief.pdf', uploadedAt: subtractDays(2) },
    ],
  },
  {
    id: 'd12',
    account: 'Tyrell Corporation',
    value: 'R$ 75K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(4),
    hasPendingDocument: true,
    documents: [],
  },

  // ── ORIGINAL: On hold (3 deals) ─────────────────────────────────
  {
    id: 'd13',
    account: 'Umbrella Corp',
    value: '$55K',
    stage: 'Proposal Sent',
    isOnHold: true,
    holdReason: 'Awaiting client budget approval',
    previousStage: 'Proposal Sent',
    lastActivityDate: subtractDays(4),
    daysPaused: 4,
    hasPendingDocument: false,
    documents: [
      { id: 'doc-13a', filename: 'Umbrella_Proposal_Q2.pdf', uploadedAt: subtractDays(10) },
    ],
  },
  {
    id: 'd14',
    account: 'Oscorp Labs',
    value: '£30K',
    stage: 'Demo Completed',
    isOnHold: true,
    holdReason: 'Decision-maker unavailable',
    previousStage: 'Demo Completed',
    lastActivityDate: subtractDays(12),
    daysPaused: 12,
    hasPendingDocument: false,
    documents: [
      { id: 'doc-14a', filename: 'Oscorp_DemoSlides.pdf', uploadedAt: subtractDays(14) },
    ],
  },
  {
    id: 'd15',
    account: 'Vandelay Industries',
    value: 'AED 45K',
    stage: 'Contacted',
    isOnHold: true,
    holdReason: 'Client requested pause',
    previousStage: 'Contacted',
    lastActivityDate: subtractDays(2),
    daysPaused: 2,
    hasPendingDocument: false,
    documents: [],
  },

  // ── NEW: Contacted stage (12 deals) ─────────────────────────────
  {
    id: 'd16',
    account: 'Meridian Logistics',
    value: '₹12L',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(1),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-16a', filename: 'Meridian_OutreachEmail.pdf', uploadedAt: subtractDays(1) },
    ],
  },
  {
    id: 'd17',
    account: 'Atlas Field Services',
    value: '$38K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(3),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd18',
    account: 'Pinnacle Manufacturing',
    value: '€ 22K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(7),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-18a', filename: 'Pinnacle_Introduction.pdf', uploadedAt: subtractDays(7) },
    ],
  },
  {
    id: 'd19',
    account: 'Horizon Facilities',
    value: 'SGD 48K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(10),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd20',
    account: 'Sterling Engineering',
    value: '₹9L',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(2),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-20a', filename: 'Sterling_DiscoveryCall.docx', uploadedAt: subtractDays(2) },
    ],
  },
  {
    id: 'd21',
    account: 'Cascade Operations',
    value: 'AUD 32K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(13),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd22',
    account: 'Apex Field Corp',
    value: 'MYR 55K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(5),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-22a', filename: 'Apex_CompanyBrief.pdf', uploadedAt: subtractDays(5) },
    ],
  },
  {
    id: 'd23',
    account: 'Primus Robotics',
    value: '$67K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(6),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd24',
    account: 'Vega Industries',
    value: '£18K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(0),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-24a', filename: 'Vega_MeetingNotes.pdf', uploadedAt: subtractDays(0) },
    ],
  },
  {
    id: 'd25',
    account: 'Sentinel Security',
    value: 'AED 62K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(8),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-25a', filename: 'Sentinel_Introduction.pdf', uploadedAt: subtractDays(8) },
    ],
  },
  {
    id: 'd26',
    account: 'Cobalt Systems',
    value: 'R$ 42K',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(14),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd27',
    account: 'Delta Logistics',
    value: '₹7.5L',
    stage: 'Contacted',
    isOnHold: false,
    lastActivityDate: subtractDays(4),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-27a', filename: 'Delta_FirstCallSummary.pdf', uploadedAt: subtractDays(4) },
    ],
  },

  // ── NEW: Demo Completed stage (9 deals) ─────────────────────────
  {
    id: 'd28',
    account: 'Nexus Group',
    value: 'SGD 70K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(2),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-28a', filename: 'Nexus_DemoFeedback.pdf', uploadedAt: subtractDays(2) },
    ],
  },
  {
    id: 'd29',
    account: 'Orion Facilities',
    value: '$54K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(7),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd30',
    account: 'Summit Manufacturing',
    value: '£45K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(3),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-30a', filename: 'Summit_DemoRecap.docx', uploadedAt: subtractDays(3) },
    ],
  },
  {
    id: 'd31',
    account: 'Frontier Services',
    value: 'MYR 95K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(9),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd32',
    account: 'Vector Technologies',
    value: '₹14L',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(1),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-32a', filename: 'Vector_TechDemoNotes.pdf', uploadedAt: subtractDays(1) },
    ],
  },
  {
    id: 'd33',
    account: 'Helios Operations',
    value: 'AED 78K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(6),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-33a', filename: 'Helios_SessionSummary.pdf', uploadedAt: subtractDays(6) },
    ],
  },
  {
    id: 'd34',
    account: 'Argon Dynamics',
    value: 'AUD 41K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(11),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd35',
    account: 'Crest Industries',
    value: 'R$ 88K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(4),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-35a', filename: 'Crest_PilotDemoReport.pdf', uploadedAt: subtractDays(4) },
    ],
  },
  {
    id: 'd36',
    account: 'Nimbus Group',
    value: '€ 33K',
    stage: 'Demo Completed',
    isOnHold: false,
    lastActivityDate: subtractDays(15),
    hasPendingDocument: true,
    documents: [],
  },

  // ── NEW: Proposal Sent stage (9 deals) ──────────────────────────
  {
    id: 'd37',
    account: 'Zenith Global',
    value: '$110K',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(2),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-37a', filename: 'Zenith_ProposalV1.pdf', uploadedAt: subtractDays(2) },
    ],
  },
  {
    id: 'd38',
    account: 'Equinox Systems',
    value: '₹18L',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(5),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-38a', filename: 'Equinox_FinalProposal.pdf', uploadedAt: subtractDays(5) },
      { id: 'doc-38b', filename: 'Equinox_Pricing_Sheet.xlsx', uploadedAt: subtractDays(3) },
    ],
  },
  {
    id: 'd39',
    account: 'Citadel Corp',
    value: 'SGD 95K',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(8),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd40',
    account: 'Tesseract Labs',
    value: '£52K',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(3),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-40a', filename: 'Tesseract_ProposalDeck.pdf', uploadedAt: subtractDays(3) },
    ],
  },
  {
    id: 'd41',
    account: 'Phoenix Operations',
    value: 'MYR 130K',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(1),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-41a', filename: 'Phoenix_CommercialProposal.pdf', uploadedAt: subtractDays(1) },
    ],
  },
  {
    id: 'd42',
    account: 'Strata Corp',
    value: 'AED 85K',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(12),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd43',
    account: 'Lighthouse Solutions',
    value: 'R$ 64K',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(6),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-43a', filename: 'Lighthouse_Proposal_Jun.pdf', uploadedAt: subtractDays(6) },
    ],
  },
  {
    id: 'd44',
    account: 'Vortex Engineering',
    value: 'AUD 73K',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(10),
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd45',
    account: 'Bedrock Industries',
    value: '₹11L',
    stage: 'Proposal Sent',
    isOnHold: false,
    lastActivityDate: subtractDays(4),
    hasPendingDocument: false,
    documents: [
      { id: 'doc-45a', filename: 'Bedrock_SolutionProposal.pdf', uploadedAt: subtractDays(4) },
    ],
  },

  // ── NEW: On hold (5 deals) ───────────────────────────────────────
  {
    id: 'd46',
    account: 'Halcyon Services',
    value: '$48K',
    stage: 'Proposal Sent',
    isOnHold: true,
    holdReason: 'Procurement / legal review',
    previousStage: 'Proposal Sent',
    lastActivityDate: subtractDays(6),
    daysPaused: 6,
    hasPendingDocument: false,
    documents: [
      { id: 'doc-46a', filename: 'Halcyon_Proposal_May.pdf', uploadedAt: subtractDays(8) },
    ],
  },
  {
    id: 'd47',
    account: 'Kronos Facilities',
    value: '£37K',
    stage: 'Demo Completed',
    isOnHold: true,
    holdReason: 'Awaiting internal approval',
    previousStage: 'Demo Completed',
    lastActivityDate: subtractDays(9),
    daysPaused: 9,
    hasPendingDocument: true,
    documents: [],
  },
  {
    id: 'd48',
    account: 'Phalanx Corp',
    value: 'AED 92K',
    stage: 'Contacted',
    isOnHold: true,
    holdReason: 'Client requested pause',
    previousStage: 'Contacted',
    lastActivityDate: subtractDays(3),
    daysPaused: 3,
    hasPendingDocument: false,
    documents: [
      { id: 'doc-48a', filename: 'Phalanx_InitialOutreach.pdf', uploadedAt: subtractDays(5) },
    ],
  },
  {
    id: 'd49',
    account: 'NovaTech Solutions',
    value: 'SGD 58K',
    stage: 'Proposal Sent',
    isOnHold: true,
    holdReason: 'Decision-maker unavailable',
    previousStage: 'Proposal Sent',
    lastActivityDate: subtractDays(15),
    daysPaused: 15,
    hasPendingDocument: false,
    documents: [
      { id: 'doc-49a', filename: 'NovaTech_ProposalV2.pdf', uploadedAt: subtractDays(17) },
    ],
  },
  {
    id: 'd50',
    account: 'Stratos Global',
    value: 'MYR 110K',
    stage: 'Demo Completed',
    isOnHold: true,
    holdReason: 'Awaiting client budget approval',
    previousStage: 'Demo Completed',
    lastActivityDate: subtractDays(7),
    daysPaused: 7,
    hasPendingDocument: false,
    documents: [
      { id: 'doc-50a', filename: 'Stratos_DemoSummary.pdf', uploadedAt: subtractDays(9) },
    ],
  },
];

// Won deals — count only, no records needed
export const WON_COUNT = 18;
